#!/bin/bash

## Description: Run programs in container, based on current host directory
## Usage: exec_d [args]
## Example: "ddev exec_d yarn"

if [ -z "$1" ]; then
  >&2 echo "No argument supplied"
  exit 1
fi

if [ "${DP_DDEV_EXEC_WARNING-0}" = 1 ]; then
  >&2 echo "Notice: running '$*' in ddev"
fi

if [ "${DP_NORMALIZE_EXEC_ARGUMENTS-1}" = 1 ] && [ -n "${GITPOD_REPO_ROOT}" ]; then
  # Replace all references to the absolute path to the repo root.
  # This will ensure IDEs like PHPStorm can pass files into it without issue.
  arguments=()
  for arg in "$@"; do
    if [ "${DP_NORMALIZE_EXEC_ARGUMENTS_TO_FULL_PATH:0}" = 1 ]; then
      # Normalize relative paths to full paths.
      if [ -e "$arg" ]; then
        arg=$(realpath "$arg")
      fi
    fi
    new_arg="${arg//${GITPOD_REPO_ROOT}//var/www/html}"
    arguments+=("$new_arg")
  done
else
  arguments=("$@")
fi

if [ "${DP_DDEV_EXEC_CHANGE_DIR-1}" = 1 ]; then
  ddev exec -d /var/www/html/"$(echo "$PWD" | cut -d'/' -f4-)" "${arguments[@]}"
else
  # Call another ddev command directly.
  ddev "${arguments[@]}"
fi
