#!/bin/bash

## Description: Run Nightwatch
## Usage: nightwatch [flags] [args]
## Example: "ddev nightwatch" or "ddev nightwatch --tag core"

cd /var/www/html/web/core || exit 2
if command -v corepack > /dev/null; then
  corepack enable
fi
# Installs dependencies if not already run.
if [ ! -d node_modules ]; then
  yarn install
fi

yarn test:nightwatch "$@"
