#!/bin/bash

## Description: Run PHPUnit
## Usage: phpunit [flags] [args]
## Example: "ddev phpunit --group big_pipe" or "ddev phpunit core/modules/action"

mkdir -p /var/www/html/web/sites/simpletest/browser_output

cd web

php /var/www/html/vendor/bin/phpunit -c /var/www/html/web/core/phpunit.xml.dist "$@"
