#!/bin/bash

## Description: Run PHPUnit
## Usage: phpunit [flags] [args]
## Example: "ddev phpunit --group big_pipe" or "ddev phpunit core/modules/action"

mkdir -p /var/www/html/web/sites/simpletest/browser_output

cd web

if [ -f /var/www/html/phpunit.xml ]; then
  phpunit_file=phpunit.xml
else
  # Fallback to the one within core.
  phpunit_file=web/core/phpunit.xml.dist
fi

php /var/www/html/vendor/bin/phpunit -c "/var/www/html/$phpunit_file" "$@"
